### ISSUE TITLE
Please remove hardcoded values. All urls etc. should be relative not absolute. 

### ISSUE THREAD

**Issue by aniketmaithani** [SHANK885/Python_Face_Detection#1]
https://github.com/SHANK885/Python_Face_Detection/blob/5b1f13cf42afcc1f6e66ef107b2f5bbb6413f8ab/face_detection.py#L126

**Comment by shank885** [comment]
Okay, Sir, I changed them to  `image_path = "Image_0.jpg"`  and it worked.
Thank you.
