### ISSUE TITLE
Don't expose your SUBSCRIPTION KEYS etc. 

### ISSUE THREAD

**Issue by aniketmaithani** [SHANK885/Python_Face_Detection#2]
put then in .env file and then read them. NEVER EXPOSE YOUR API KEYS PUBLICLY! 

https://stackoverflow.com/questions/40216311/reading-in-environment-variables-from-an-environment-file

Keep your keys in .env file and put .env file in .gitignore file 

Read about .env and .gitignore.

**Comment by shank885** [comment]
Okey Sir
